" Information {{{
"       Author: Alberto Montes
" }}}

" Plugins {{{
        set nocompatible
        filetype off
        set runtimepath+=~/.vim/bundle/Vundle.vim
        set runtimepath+=/usr/local/opt/fzf
        call vundle#begin()

        Plugin 'VundleVim/Vundle.vim'
        " UI: airline + theme
        Plugin 'vim-airline/vim-airline'
        Plugin 'vim-airline/vim-airline-themes'
        Plugin 'morhetz/gruvbox'
        Plugin 'ryanoasis/vim-devicons'
        " IDE: utils
        Plugin 'scrooloose/nerdtree'
        Bundle 'jistr/vim-nerdtree-tabs'
        Plugin 'Xuyuanp/nerdtree-git-plugin'
        Plugin 'majutsushi/tagbar'
        Plugin 'kien/ctrlp.vim'
        Plugin 'junegunn/fzf'
        Plugin 'valloric/youcompleteme'
        " Plugin 'mileszs/ack.vim'
        Plugin 'qpkorr/vim-bufkill'
        Plugin 'tpope/vim-eunuch'
        Plugin 'SirVer/ultisnips'
        Plugin 'honza/vim-snippets'
        " Vim as a programmer's text editor
        Plugin 'tpope/vim-sensible'
        Plugin 'tpope/vim-commentary'
        Plugin 'terryma/vim-multiple-cursors'
        Plugin 'xolox/vim-misc'
        Plugin 'tpope/vim-surround'
        Plugin 'editorconfig/editorconfig-vim'
        " Plugin 'Valloric/YouCompleteMe'
        Plugin 'tpope/vim-unimpaired'
        Plugin 'rizzatti/dash.vim'
        Plugin 'Raimondi/delimitMate'
        " LaTeX
        Plugin 'lervag/vimtex'
        " Git
        Plugin 'airblade/vim-gitgutter'
        Plugin 'tpope/vim-fugitive'
        " tmux
        Plugin 'christoomey/vim-tmux-navigator'
        " Syntax
        Plugin 'w0rp/ale'
        " Markdown
        Plugin 'godlygeek/tabular'
        Plugin 'plasticboy/vim-markdown'
        " Web Development
        Plugin 'othree/html5.vim'

        call vundle#end()
" }}}

" General Settings {{{
        filetype plugin indent on
        " UI config
        set background=dark
        colorscheme gruvbox
        syntax on
        set laststatus=2				" Always show statusbar
        " Config number lines
        set number relativenumber
        " Show line number in INSERT mode, and relative line numbers in NORMAL mode
        augroup numbertoggle
                autocmd!
                autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
                autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
        augroup END

        " Tabulation
        set expandtab

        set cursorline
        set wildmenu
        set exrc
        set lazyredraw
        set showmatch
        set colorcolumn=+1        " highlight column after 'textwidth'
        set encoding=utf-8
        " set shortmess=a
        " search
        set incsearch
        set hlsearch
        " folding
        set foldenable
        set foldlevelstart=10
        set foldnestmax=10
        set foldmethod=indent
        set conceallevel=2

        set clipboard=unnamed

        set backspace=indent,eol,start
        set ruler
        set termguicolors
        highlight Comment cterm=italic

        syntax on

        if has('mouse')
                set mouse=a
        endif

        if has('nvim')
                let g:python_host_prog = '/usr/local/bin/python2'
                let g:python3_host_prog = '/usr/local/bin/python3'
        endif

        set secure
" }}}


" Mappings {{{
        " nnoremap <C-p> :FZF<CR>
        nnoremap <leader><space> :nohlsearch<CR>
        inoremap jj <ESC><CR>
        map <C-w> :BD<CR>:redraw<CR>
        nmap <C-e> :e#<CR>

        nmap j gj
        nmap k gk
" }}}
